version: '3'
services:
  first-container:
    build:
      context:
        dockerfile: Dockerfile
        second-container:
          image: nginx
          ports:
            - "80:8080"
          volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          depends_on:
            - first-container
